struct IOData {
  u16 *address;
  u16 offset;
  TCHAR *name;
  u16 write;
  TCHAR *bits[16];
};

const IOData ioViewRegisters[] = {
  {
    &DISPCNT, 0, _T("0x4000000-DISPCNT"), 0xFFF7,
    {
      _T(""),
      _T(""),
      _T("BG Mode (3 bits)"),
      _T("CGB Mode"),
      _T("Display Frame"),
      _T("H-Blank Interval OBJ processing"),
      _T("OBJ Character mapping"),
      _T("Forced blank"),
      _T("BG0"),
      _T("BG1"),
      _T("BG2"),
      _T("BG3"),
      _T("OBJ"),
      _T("WIN0"),
      _T("WIN1"),
      _T("OBJWIN")
    }
  },
  {
    &DISPSTAT, 4, _T("0x4000004-DISPSTAT"), 0xFF38,
    {
      _T("V-Blank Status"),
      _T("H-Blank Status"),
      _T("VCOUNT Evaluation"),
      _T("V-Blank Interrupt Enable"),
      _T("H-Blank Interrupt Enable"),
      _T("VCOUNT Match Interrupt Enable"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("VCOUNT setting (8 bits)")
    }
  },
  {
    &VCOUNT, 6, _T("0x4000006-VCOUNT"), 0x0000,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("VCOUNT (8 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("")
    }
  },
  {
    &BG0CNT, 8, _T("0x4000008-BG0CNT"), 0xDFCF,
    {
      _T(""),
      _T("Priority (2 bits)"),
      _T(""),
      _T("Char base (2 bits)"),
      _T(""),
      _T(""),
      _T("Mosaic"),
      _T("16/256 colors"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Screen Base Block (5 bits)"),
      _T(""),
      _T(""),
      _T("Size (2 bits)")
    }
  },
  {
    &BG1CNT, 0xA, _T("0x400000A-BG1CNT"), 0xDFCF,
    {
      _T(""),
      _T("Priority (2 bits)"),
      _T(""),
      _T("Char base (2 bits)"),
      _T(""),
      _T(""),
      _T("Mosaic"),
      _T("16/256 colors"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Screen Base Block (5 bits)"),
      _T(""),
      _T(""),
      _T("Size (2 bits)")
    }
  },
  {
    &BG2CNT, 0xC, _T("0x400000C-BG2CNT"), 0xFFCF,
    {
      _T(""),
      _T("Priority (2 bits)"),
      _T(""),
      _T("Char base (2 bits)"),
      _T(""),
      _T(""),
      _T("Mosaic"),
      _T("16/256 colors"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Screen Base Block (5 bits)"),
      _T("Area Overflow"),
      _T(""),
      _T("Size (2 bits)")
    }
  },
  {
    &BG3CNT, 0xE, _T("0x400000E-BG3CNT"), 0xFFCF,
    {
      _T(""),
      _T("Priority (2 bits)"),
      _T(""),
      _T("Char base (2 bits)"),
      _T(""),
      _T(""),
      _T("Mosaic"),
      _T("16/256 colors"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Screen Base Block (5 bits)"),
      _T("Area Overflow"),
      _T(""),
      _T("Size (2 bits)")
    }
  },
  {
    &BG0HOFS, 0x10, _T("0x4000010-BG0HOFS"), 0x01FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Horizontal Offset (9 bits, W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("")
    }
  },
  {
    &BG0VOFS, 0x12, _T("0x4000012-BG0VOFS"), 0x01FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Vertical Offset (9 bits, W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("")
    }
  },
  {
    &BG1HOFS, 0x14, _T("0x4000014-BG1HOFS"), 0x01FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Horizontal Offset (9 bits, W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("")
    }
  },
  {
    &BG1VOFS, 0x16, _T("0x4000016-BG1VOFS"), 0x01FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Vertical Offset (9 bits, W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("")
    }
  },
  {
    &BG2HOFS, 0x18, _T("0x4000018-BG2HOFS"), 0x01FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Horizontal Offset (9 bits, W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("")
    }
  },
  {
    &BG2VOFS, 0x1A, _T("0x400001A-BG2VOFS"), 0x01FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Vertical Offset (9 bits, W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("")
    }
  },
  {
    &BG3HOFS, 0x1C, _T("0x400001C-BG3HOFS"), 0x01FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Horizontal Offset (9 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("")
    }
  },
  {
    &BG3VOFS, 0x1E, _T("0x400001E-BG3VOFS"), 0x01FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Vertical Offset (9 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("")
    }
  },
  {
    &BG2PA, 0x20, _T("0x4000020-BG2PA"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("dx (16 bits,W)")
    }
  },
  {
    &BG2PB, 0x22, _T("0x4000022-BG2PB"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("dmx (16 bits,W)")
    }
  },
  {
    &BG2PC, 0x24, _T("0x4000024-BG2PC"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("dy (16 bits,W)")
    }
  },
  {
    &BG2PD, 0x26, _T("0x4000026-BG2PD"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("dmy (16 bits,W)")
    }
  },
  {
    &BG2X_L, 0x28, _T("0x4000028-BG2X_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("X low bits (16 bits,W)")
    }
  },
  {
    &BG2X_H, 0x2A, _T("0x400002A-BG2X_H"), 0x0FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("X high bits (12 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &BG2Y_L, 0x2C, _T("0x400002C-BG2Y_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Y low bits (16 bits,W)")
    }
  },
  {
    &BG2Y_H, 0x2E, _T("0x400002E-BG2Y_H"), 0x0FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Y hight bits (12 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &BG3PA, 0x30, _T("0x4000030-BG3PA"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("dx (16 bits,W)")
    }
  },
  {
    &BG3PB, 0x32, _T("0x4000032-BG3PB"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("dmx (16 bits,W)")
    }
  },
  {
    &BG3PC, 0x34, _T("0x4000034-BG3PC"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("dy (16 bits,W)")
    }
  },
  {
    &BG3PD, 0x36, _T("0x4000036-BG3PD"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("dmy (16 bits,W)")
    }
  },
  {
    &BG3X_L, 0x38, _T("0x4000038-BG3X_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("X low bits (16 bits,W)")
    }
  },
  {
    &BG3X_H, 0x3A, _T("0x400003A-BG3X_H"), 0x0FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("X hight bits (12 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &BG3Y_L, 0x3C, _T("0x400003C-BG3Y_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Y low bits (16 bits,W)")
    }
  },
  {
    &BG3Y_H, 0x3E, _T("0x400003E-BG3Y_H"), 0x0FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Y hight bits (12 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &WIN0H, 0x40, _T("0x4000040-WIN0H"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Win 0 lower-right X (8 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Win 0 upper-left X (8 bits,W)"),
    }
  },
  {
    &WIN1H, 0x42, _T("0x4000042-WIN1H"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Win 1 lower-right X (8 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Win 1 upper-left (8 bits,W)"),
    }
  },
  {
    &WIN0V, 0x44, _T("0x4000044-WIN0V"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Win 0 lower-right Y (8 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Win 0 upper-left Y (8 bits,W)"),
    }
  },
  {
    &WIN1V, 0x46, _T("0x4000046-WIN1V"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Win 1 lower-right Y (8 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Win 1 upper-left Y (8 bits,W)"),
    }
  },
  {
    &WININ, 0x48, _T("0x4000048-WININ"), 0x3F3F,
    {
      _T("WIN0 BG0"),
      _T("WIN0 BG1"),
      _T("WIN0 BG2"),
      _T("WIN0 BG3"),
      _T("WIN0 OBJ"),
      _T("WIN0 Special FX"),
      _T(""),
      _T(""),
      _T("WIN1 BG0"),
      _T("WIN1 BG1"),
      _T("WIN1 BG2"),
      _T("WIN1 BG3"),
      _T("WIN1 OBJ"),
      _T("WIN1 Special FX"),
      _T(""),
      _T(""),
    }
  },
  {
    &WINOUT, 0x4A, _T("0x400004A-WINOUT"), 0x3F3F,
    {
      _T("WIN0/1 BG0"),
      _T("WIN0/1 BG1"),
      _T("WIN0/1 BG2"),
      _T("WIN0/1 BG3"),
      _T("WIN0/1 OBJ"),
      _T("WIN0/1 Special FX"),
      _T(""),
      _T(""),
      _T("OBJWIN BG0"),
      _T("OBJWIN BG1"),
      _T("OBJWIN BG2"),
      _T("OBJWIN BG3"),
      _T("OBJWIN OBJ"),
      _T("OBJWIN Special FX"),
      _T(""),
      _T(""),
    }
  },
  {
    &MOSAIC, 0x4C, _T("0x400004C-MOSAIC"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T("BG H Size (4 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T("BG V Size (4 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T("OBJ H Size (4 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T("OBJ V Size (4 bits,W)"),
    }
  },
  {
    &BLDMOD, 0x50, _T("0x4000050-BLDMOD"), 0x3FFF,
    {
      _T("1st BG0"),
      _T("1st BG1"),
      _T("1st BG2"),
      _T("1st BG3"),
      _T("1st OBJ"),
      _T("1st BD"),
      _T(""),
      _T("FX Type (2 bits)"),
      _T("2nd BG0"),
      _T("2nd BG1"),
      _T("2nd BG2"),
      _T("2nd BG3"),
      _T("2nd OBJ"),
      _T("2nd BD"),
      _T(""),
      _T(""),
    }
  },
  {
    &COLEV, 0x52, _T("0x4000052-COLEV"), 0x1F1F,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Coefficient EVA (5 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Coefficient EVB (5 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &COLY, 0x54, _T("0x4000054-COLEY"), 0x001F,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Coefficient EVY (5 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    NULL, 0x60, _T("0x4000060-SG10_L"), 0x007F,
    {
      _T(""),
      _T(""),
      _T("Sweep Shifts (3 bits)"),
      _T("Sweep addition/decrease"),
      _T(""),
      _T(""),
      _T("Sweep Time (3 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    NULL, 0x62, _T("0x4000062-SG10_H"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Sound Length (6 bits,W)"),
      _T(""),
      _T("Waveform Type (2 bits)"),
      _T(""),
      _T(""),
      _T("Envelope Steps (3 bits)"),
      _T("Envelope Attenuate/Amplify"),
      _T(""),
      _T(""),
      _T(""),
      _T("Envelope Initial Value"),
    }
  },
  {
    NULL, 0x64, _T("0x4000064-SG11"), 0xC7FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Frequency (11 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T("Sound Continuous/Counter"),
      _T("Initialization (W)"),
    }
  },
  {
    NULL, 0x68, _T("0x4000068-SG20"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Sound Length (6 bits,W)"),
      _T(""),
      _T("Waveform Type (2 bits)"),
      _T(""),
      _T(""),
      _T("Envelope Steps (3 bits)"),
      _T("Envelope Attenuate/Amplify"),
      _T(""),
      _T(""),
      _T(""),
      _T("Envelope Initial Value"),
    }
  },
  {
    NULL, 0x6C, _T("0x400006C-SG21"), 0xC7FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Frequency (11 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T("Sound Continuous/Counter"),
      _T("Initialization (W)"),
    }
  },
  {
    NULL, 0x70, _T("0x4000070-SG30_L"), 0x00E0,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Waveform 32/64 Steps"),
      _T("Waveform Bank 0/1"),
      _T("Sound Output"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    NULL, 0x72, _T("0x4000072-SG30_H"), 0xE0FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Sound Length (8 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Output Level (2 bits)"),
      _T("Forced 3/4 Output Level"),
    }
  },
  {
    NULL, 0x74, _T("0x4000074-SG31"), 0xC7FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Frequency (11 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T("Sound Continuous/Counter"),
      _T("Initialization (W)"),
    }
  },
  {
    NULL, 0x78, _T("0x4000078-SG40"), 0xFF3F,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Sound Length (6 bits,W)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Envelope Steps (3 bits)"),
      _T("Envelope Attenuate/Amplify"),
      _T(""),
      _T(""),
      _T(""),
      _T("Envelope Initial Value"),
    }
  },
  {
    NULL, 0x7C, _T("0x400007C-SG41"), 0xC0FF,
    {
      _T(""),
      _T(""),
      _T("Dividing Ratio Freq. (3 bits)"),
      _T("Counter 15/7 Steps"),
      _T(""),
      _T(""),
      _T(""),
      _T("Counter Shift Clock (4 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Sound Continuous/Counter"),
      _T("Initialization (W)"),
    }
  },
  {
    NULL, 0x80, _T("0x4000080-SGCNT0_L"), 0xFF77,
    {
      _T(""),
      _T(""),
      _T("Right Volume (3 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T("Left Volume (3 bits)"),
      _T(""),
      _T("Channel 1->Right"),
      _T("Channel 2->Right"),
      _T("Channel 3->Right"),
      _T("Channel 4->Right"),
      _T("Channel 1->Left"),
      _T("Channel 2->Left"),
      _T("Channel 3->Left"),
      _T("Channel 4->Left"),
    }
  },
  {
    NULL, 0x82, _T("0x4000082-SGCNT0_H"), 0xFF0F,
    {
      _T(""),
      _T("Sound 1-4 Volume (2 bits)"),
      _T("DMA Sound A Volume"),
      _T("DMA Sound B Volume"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("DMA Sound A->Right"),
      _T("DMA Sound A->Left"),
      _T("DMA Sound A Timer"),
      _T("DMA Sound A Reset FIFO"),
      _T("DMA Sound B->Right"),
      _T("DMA Sound B->Left"),
      _T("DMA Sound B Timer"),
      _T("DMA Sound B Reset FIFO"),
    }
  },
  {
    NULL, 0x84, _T("0x4000084-SGCNT1"), 0x0080,
    {
      _T("Sound 1 On"),
      _T("Sound 2 On"),
      _T("Sound 3 On"),
      _T("Sound 4 On"),
      _T(""),
      _T(""),
      _T(""),
      _T("Master Sound Enable"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    NULL, 0x88, _T("0x4000088-SGBIAS"), 0xC3FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Bias Level (10 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Sampling Rate (2 bits)"),
    }
  },
  {
    NULL, 0xA0, _T("0x40000A0-SIGFIFOA_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Data 0 (8 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Data 1 (8 bits)"),
    }
  },
  {
    NULL, 0xA2, _T("0x40000A2-SIGFIFOA_H"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Data 2 (8 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Data 3 (8 bits)"),
    }
  },
  {
    NULL, 0xA4, _T("0x40000A4-SIGFIFOB_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Data 0 (8 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Data 1 (8 bits)"),
    }
  },
  {
    NULL, 0xA6, _T("0x40000A6-SIGFIFOB_H"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Data 2 (8 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Data 3 (8 bits)"),
    }
  },
  {
    &DM0SAD_L, 0xB0, _T("0x40000B0-DM0SAD_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Source Address (lower 16 bits)"),
    }
  },
  {
    &DM0SAD_H, 0xB2, _T("0x40000B2-DM0SAD_H"), 0x07FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Source Address (upper 11 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &DM0DAD_L, 0xB4, _T("0x40000B4-DM0DAD_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address (lower 16 bits)"),
    }
  },
  {
    &DM0DAD_H, 0xB6, _T("0x40000B6-DM0DAD_H"), 0x07FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address (upper 11 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &DM0CNT_L, 0xB8, _T("0x40000B8-DM0CNT_L"), 0x3FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Count (14 bits)"),
      _T(""),
      _T(""),
    }
  },
  {
    &DM0CNT_H, 0xBA, _T("0x40000BA-DM0CNT_H"), 0xF7E0,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address Control (2 bits)"),
      _T(""),
      _T("Source Address Control (2 bits)"),
      _T("Repeat"),
      _T("Transfer Type"),
      _T(""),
      _T(""),
      _T("Start Timing (2 bits)"),
      _T("Interrupt Request"),
      _T("Enable"),
    }
  },
  {
    &DM1SAD_L, 0xBC, _T("0x40000BC-DM1SAD_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Source Address (lower 16 bits)"),
    }
  },
  {
    &DM1SAD_H, 0xBE, _T("0x40000BE-DM1SAD_H"), 0x0FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Source Address (upper 12 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &DM1DAD_L, 0xC0, _T("0x40000C0-DM1DAD_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address (lower 16 bits)"),
    }
  },
  {
    &DM1DAD_H, 0xC2, _T("0x40000C2-DM1DAD_H"), 0x07FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address (upper 11 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &DM1CNT_L, 0xC4, _T("0x40000C4-DM1CNT_L"), 0x3FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Count (14 bits)"),
      _T(""),
      _T(""),
    }
  },
  {
    &DM1CNT_H, 0xC6, _T("0x40000C6-DM1CNT_H"), 0xF7E0,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address Control (2 bits)"),
      _T(""),
      _T("Source Address Control (2 bits)"),
      _T("Repeat"),
      _T("Transfer Type"),
      _T(""),
      _T(""),
      _T("Start Timing (2 bits)"),
      _T("Interrupt Request"),
      _T("Enable"),
    }
  },
  {
    &DM2SAD_L, 0xC8, _T("0x40000C8-DM2SAD_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Source Address (lower 16 bits)"),
    }
  },
  {
    &DM2SAD_H, 0xCA, _T("0x40000CA-DM2SAD_H"), 0x0FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Source Address (upper 12 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &DM2DAD_L, 0xCC, _T("0x40000CC-DM2DAD_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address (lower 16 bits)"),
    }
  },
  {
    &DM2DAD_H, 0xCE, _T("0x40000CE-DM2DAD_H"), 0x07FF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address (upper 11 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &DM2CNT_L, 0xD0, _T("0x40000D0-DM2CNT_L"), 0x3FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Count (14 bits)"),
      _T(""),
      _T(""),
    }
  },
  {
    &DM2CNT_H, 0xD2, _T("0x40000D2-DM2CNT_H"), 0xF7E0,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address Control (2 bits)"),
      _T(""),
      _T("Source Address Control (2 bits)"),
      _T("Repeat"),
      _T("Transfer Type"),
      _T(""),
      _T(""),
      _T("Start Timing (2 bits)"),
      _T("Interrupt Request"),
      _T("Enable"),
    }
  },
  {
    &DM3SAD_L, 0xD4, _T("0x40000D4-DM3SAD_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Source Address (lower 16 bits)"),
    }
  },
  {
    &DM3SAD_H, 0xD6, _T("0x40000D6-DM3SAD_H"), 0x0FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Source Address (upper 12 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &DM3DAD_L, 0xD8, _T("0x40000D8-DM3DAD_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address (lower 16 bits)"),
    }
  },
  {
    &DM3DAD_H, 0xDA, _T("0x40000DA-DM3DAD_H"), 0x0FFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address (upper 12 bits)"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &DM3CNT_L, 0xDC, _T("0x40000DC-DM3CNT_L"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Count (16 bits)"),
    }
  },
  {
    &DM3CNT_H, 0xDE, _T("0x40000DE-DM3CNT_H"), 0xFFE0,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Destination Address Control (2 bits)"),
      _T(""),
      _T("Source Address Control (2 bits)"),
      _T("Repeat"),
      _T("Transfer Type"),
      _T("Game Pak Data Request"),
      _T(""),
      _T("Start Timing (2 bits)"),
      _T("Interrupt Request"),
      _T("Enable"),
    }
  },
  {
    &TM0D, 0x100, _T("0x4000100-TM0D"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Timer Counter (16 bits)"),
    }
  },
  {
    &TM0CNT, 0x102, _T("0x4000102-TM0CNT"), 0x00C7,
    {
      _T(""),
      _T("Scalar Selection (2 bits)"),
      _T("Count Up"),
      _T(""),
      _T(""),
      _T(""),
      _T("Interrupt Request"),
      _T("Enable"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &TM1D, 0x104, _T("0x4000104-TM1D"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Timer Counter (16 bits)"),
    }
  },
  {
    &TM1CNT, 0x106, _T("0x4000106-TM1CNT"), 0x00C7,
    {
      _T(""),
      _T("Scalar Selection (2 bits)"),
      _T("Count Up"),
      _T(""),
      _T(""),
      _T(""),
      _T("Interrupt Request"),
      _T("Enable"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &TM2D, 0x108, _T("0x4000108-TM2D"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Timer Counter (16 bits)"),
    }
  },
  {
    &TM2CNT, 0x10A, _T("0x400010A-TM2CNT"), 0x00C7,
    {
      _T(""),
      _T("Scalar Selection (2 bits)"),
      _T("Count Up"),
      _T(""),
      _T(""),
      _T(""),
      _T("Interrupt Request"),
      _T("Enable"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &TM3D, 0x10C, _T("0x400010C-TM3D"), 0xFFFF,
    {
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Timer Counter (16 bits)"),
    }
  },
  {
    &TM3CNT, 0x10E, _T("0x400010E-TM3CNT"), 0x00C7,
    {
      _T(""),
      _T("Scalar Selection (2 bits)"),
      _T("Count Up"),
      _T(""),
      _T(""),
      _T(""),
      _T("Interrupt Request"),
      _T("Enable"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    &P1, 0x130, _T("0x4000130-P1"), 0x03FF,
    {
      _T("A"),
      _T("B"),
      _T("Select"),
      _T("Start"),
      _T("Right"),
      _T("Left"),
      _T("Up"),
      _T("Down"),
      _T("Shoulder Right"),
      _T("Shoulder Left"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    NULL, 0x132, _T("0x4000132-P1CNT"), 0xC3FF,
    {
      _T("A"),
      _T("B"),
      _T("Select"),
      _T("Start"),
      _T("Right"),
      _T("Left"),
      _T("Up"),
      _T("Down"),
      _T("Shoulder Right"),
      _T("Shoulder Left"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Interrupt Request"),
      _T("Interrupt Condition"),
    }
  },
  {
    &IE, 0x200, _T("0x4000200-IE"), 0x3FFF,
    {
      _T("VBlank"),
      _T("HBlank"),
      _T("VCount"),
      _T("Timer 0"),
      _T("Timer 1"),
      _T("Timer 2"),
      _T("Timer 3"),
      _T("Serial"),
      _T("DMA 0"),
      _T("DMA 1"),
      _T("DMA 2"),
      _T("DMA 3"),
      _T("Keypad"),
      _T("Game Pak"),
      _T(""),
      _T(""),
    }
  },
  {
    &IF, 0x202, _T("0x4000202-IF"), 0x0000,
    {
      _T("VBlank"),
      _T("HBlank"),
      _T("VCount"),
      _T("Timer 0"),
      _T("Timer 1"),
      _T("Timer 2"),
      _T("Timer 3"),
      _T("Serial"),
      _T("DMA 0"),
      _T("DMA 1"),
      _T("DMA 2"),
      _T("DMA 3"),
      _T("Keypad"),
      _T("Game Pak"),
      _T(""),
      _T(""),
    }
  },
  {
    NULL, 0x204, _T("0x4000204-WAITCNT"), 0x5FFF,
    {
      _T(""),
      _T("SRAM Wait Control (2 bits)"),
      _T(""),
      _T("Wait State 0 First Access (2 bits)"),
      _T("Wait State 0 Second Access"),
      _T(""),
      _T("Wait State 1 First Access (2 bits)"),
      _T("Wait State 1 Second Access"),
      _T(""),
      _T("Wait State 2 First Access (2 bits)"),
      _T("Wait State 2 Second Access"),
      _T(""),
      _T("PHI Terminal Output (2 bits)"),
      _T(""),
      _T("Game Pak Prefetch Buffer"),
      _T("Game Pak Type Flag"),
    }
  },
  {
    &IME, 0x208, _T("0x4000208-IME"), 0x0001,
    {
      _T("Master Interrupt Enable"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
    }
  },
  {
    NULL, 0x300, _T("0x4000300-HALTCNT"), 0x8001,
    {
      _T("First Boot"),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T(""),
      _T("Power Down"),
    }
  },
};
